Repository lint-todo/stylelint-formatter-todo, pull requests merged in 2022-10, with the labels that each got.

#53 Ensure correct stylelint versions are being used
  package-lock.json
  package.json
  src/index.ts
  yarn.lock
Labels: enhancement

#55 Implements FORMAT_TODO_AS functionality.
  __tests__/acceptance/stylelint-formatter-todo-test.ts
  __tests__/unit/formatter-test.ts
  __tests__/unit/get-formatter-test.ts
  __tests__/unit/utils-test.ts
  package.json
  src/formatter.ts
  src/get-base-dir.ts
  src/get-formatter.ts
  src/index.ts
  src/print-results.ts
  src/terminal-link.ts
  src/types/common-tags.d.ts
  src/types/index.ts
  src/types/stylelint-sarif-formatter.d.ts
  src/types/supports-hyperlinks.d.ts
Labels: enhancement, internal

#56 Adds source extraction to enable fuzzy matching
  src/formatter.ts
Labels: enhancement, internal

#57 Use source utils from @lint-todo/utils
  __tests__/__fixtures__/with-fixable-error.css
  __tests__/acceptance/stylelint-formatter-todo-test.ts
  package-lock.json
  package.json
  src/formatter.ts
Labels: internal
